#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

bin_dir="$(pwd)/_output/bin"
mkdir -p ${bin_dir} || true

function go_build {
	if [ ! -z ${GOINSTALL+x} ] && [ "${GOINSTALL}" = "y" ]
	then
  		GOBIN=${bin_dir} GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go install -installsuffix cgo ./cmd/${1}/
	else
  		GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${bin_dir}/${1} -installsuffix cgo ./cmd/${1}/
	fi
}

go_build prober-operator
go_build prober

docker build --tag "${IMAGE}" -f ./hack/operator/Dockerfile . 1>/dev/null
docker push "${IMAGE}" 1>/dev/null
